if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    set(ECM_OS_WINDOWS 1)
    if("${CMAKE_GENERATOR_PLATFORM}" MATCHES "ARM64" OR "${MSVC_CXX_ARCHITECTURE_ID}" MATCHES "ARM64" OR "${CMAKE_SYSTEM_PROCESSOR}" MATCHES "ARM64")
        set(ARCH_ARM64 1)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(ARCH_X86 1)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(ARCH_X64 1)
    else()
        message(FATAL_ERROR "Unsupported windows architecture")
        return()
    endif()
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
    set(ECM_OS_UNIX 1)
    if(ANDROID)
        set(ECM_OS_ANDROID 1)
    else()
        set(ECM_OS_LINUX 1)
    endif()
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "^k?FreeBSD$")
    set(ECM_OS_FREEBSD 1)
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "^OpenBSD$")
    set(ECM_OS_OPENBSD 1)
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "^NetBSD$")
    set(ECM_OS_NETBSD 1)
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "iOS")
    set(ECM_OS_IOS 1)
    message(FATAL_ERROR "Unsupported operating system")
    return()
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Darwin")
    set(ECM_OS_MACOS 1)
    message(FATAL_ERROR "Unsupported operating system")
    return()
elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Android")
    set(ECM_OS_ANDROID 1)
endif()
